# Generated by Django 4.2.1 on 2023-05-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='image',
            field=models.ImageField(upload_to='product', verbose_name='Фото'),
        ),
    ]
