# Generated by Django 4.2.1 on 2023-05-14 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_orders_status_delete_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='delivery',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
