# Generated by Django 4.2.1 on 2023-05-14 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_orders_delivery_delete_delivery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
    ]
