# Generated by Django 4.2.1 on 2023-05-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_rename_orders_order_rename_orderdetails_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_sum',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Итоговая сумма'),
        ),
    ]
