# Generated by Django 4.2.1 on 2023-06-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_dessert_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='pay',
            options={'verbose_name': 'Способ оплаты', 'verbose_name_plural': 'Способы оплаты'},
        ),
    ]
